spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT}
  datasource:
    url: ${datasource-url}
    username: ${datassource-username}
    password: ${datasource-password}
  jpa:
    hibernate:
      ddl-auto: none #empêcher spring de gerer les requêtes
